name: PulsePrisonAddonExample
version: '${version}'
main: dev.devmodee.pulseprisonaddon.PulsePrisonAddon
api-version: '1.20'
depend: [PulsePrison]
authors: [DevModee]
description: An example add-on to demonstrate the PulsePrison Developer API.
